"""add_satellites_and_fix_hdop_type

Revision ID: 33cfaa88d79b
Revises: 7c0329f8f105
Create Date: 2026-06-10 13:41:15.971876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33cfaa88d79b'
down_revision: Union[str, Sequence[str], None] = '7c0329f8f105'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telemetry', sa.Column('satellites', sa.Integer(), nullable=True))
    op.alter_column('telemetry', 'hdop',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('telemetry', 'hdop',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('telemetry', 'satellites')
    # ### end Alembic commands ###
