"""Add min_firmware_version to OtaRelease

Revision ID: 7c0329f8f105
Revises: c7b92e8b4ee6
Create Date: 2026-06-04 00:14:29.132451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c0329f8f105'
down_revision: Union[str, Sequence[str], None] = 'c7b92e8b4ee6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ota_releases', sa.Column('min_firmware_version', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ota_releases', 'min_firmware_version')
    # ### end Alembic commands ###
