"""Initial TimescaleDB schema

Revision ID: c7b92e8b4ee6
Revises:
Create Date: 2026-06-01 04:18:27.460538

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c7b92e8b4ee6"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Enable Timescale
    op.execute("CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;")
    op.create_table(
        "devices",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("imei", sa.String(length=15), nullable=False),
        sa.Column("firmware_version", sa.String(), nullable=True),
        sa.Column("sim_iccid", sa.String(length=22), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_devices_imei"), "devices", ["imei"], unique=True)
    op.create_index(
        op.f("ix_devices_sim_iccid"), "devices", ["sim_iccid"], unique=False
    )
    op.create_table(
        "ota_releases",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("version", sa.String(), nullable=False),
        sa.Column("firmware_url", sa.String(), nullable=False),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=False),
        sa.Column("is_stable", sa.Boolean(), nullable=False),
        sa.Column(
            "released_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ota_releases_version"), "ota_releases", ["version"], unique=True
    )
    op.create_table(
        "ota_jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column("release_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["release_id"], ["ota_releases.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ota_jobs_device_id"), "ota_jobs", ["device_id"], unique=False
    )
    op.create_index(op.f("ix_ota_jobs_status"), "ota_jobs", ["status"], unique=False)
    op.create_table(
        "telemetry",
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.Text(), nullable=True),
        sa.Column("device_ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "server_ts",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("latitude", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("altitude_m", sa.Float(), nullable=True),
        sa.Column("speed_kmh", sa.Float(), nullable=True),
        sa.Column("heading_deg", sa.Float(), nullable=True),
        sa.Column("accuracy_m", sa.Float(), nullable=True),
        sa.Column("hdop", sa.Integer(), nullable=True),
        sa.Column("fix_quality", sa.Integer(), nullable=True),
        sa.Column("gps_ttff", sa.Float(), nullable=True),
        sa.Column("rssi", sa.Integer(), nullable=True),
        sa.Column("rsrp", sa.Integer(), nullable=True),
        sa.Column("rsrq", sa.Integer(), nullable=True),
        sa.Column("cell_id", sa.Text(), nullable=True),
        sa.Column("cpsi_raw", sa.Text(), nullable=True),
        sa.Column("battery_voltage", sa.Float(), nullable=True),
        sa.Column("battery_pct", sa.Float(), nullable=True),
        sa.Column("accel_x", sa.Float(), nullable=True),
        sa.Column("accel_y", sa.Float(), nullable=True),
        sa.Column("accel_z", sa.Float(), nullable=True),
        sa.Column("accel_magnitude", sa.Float(), nullable=True),
        sa.Column("is_moving", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("device_id", "device_ts"),
    )
    op.create_index(
        op.f("ix_telemetry_cell_id"), "telemetry", ["cell_id"], unique=False
    )
    op.create_index(
        "ix_telemetry_event_time",
        "telemetry",
        ["event_type", "device_ts"],
        unique=False,
    )
    op.create_index(
        op.f("ix_telemetry_event_type"), "telemetry", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_telemetry_server_ts"), "telemetry", ["server_ts"], unique=False
    )
    # 2. Convert to Hypertable
    op.execute(
        "SELECT create_hypertable('telemetry', 'device_ts', chunk_time_interval => INTERVAL '1 day', if_not_exists => TRUE);"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_telemetry_server_ts"), table_name="telemetry")
    op.drop_index(op.f("ix_telemetry_event_type"), table_name="telemetry")
    op.drop_index("ix_telemetry_event_time", table_name="telemetry")
    op.drop_index(op.f("ix_telemetry_cell_id"), table_name="telemetry")
    op.drop_table("telemetry")
    op.drop_index(op.f("ix_ota_jobs_status"), table_name="ota_jobs")
    op.drop_index(op.f("ix_ota_jobs_device_id"), table_name="ota_jobs")
    op.drop_table("ota_jobs")
    op.drop_index(op.f("ix_ota_releases_version"), table_name="ota_releases")
    op.drop_table("ota_releases")
    op.drop_index(op.f("ix_devices_sim_iccid"), table_name="devices")
    op.drop_index(op.f("ix_devices_imei"), table_name="devices")
    op.drop_table("devices")
    # ### end Alembic commands ###
